; --------------------------------------------------------------------------------------------------
;                           bhsupp.inc Copyright The MASM32 SDK 1998-2010
; --------------------------------------------------------------------------------------------------

IFNDEF BHSUPP_INC
BHSUPP_INC equ <1>

  ; dprintf arg type unknown

ELSE
  echo -----------------------------------------
  echo WARNING duplicate include file bhsupp.inc
  echo -----------------------------------------
ENDIF
