@echo off
  inc2l 1394bus.inc
  inc2l acledit.inc
  inc2l aclui.inc
  inc2l acpisim.inc
  inc2l activeds.inc
  inc2l adptif.inc
  inc2l advapi32.inc
  inc2l advapip.inc
  inc2l advpack.inc
  inc2l apidll.inc
  inc2l appmgmts.inc
  inc2l arbiter.inc
  inc2l asycfilt.inc
  inc2l authz.inc
  inc2l basesrv.inc
  inc2l batmeter.inc
  inc2l battc.inc
  inc2l bdasup.inc
  inc2l bhsupp.inc
  inc2l bignumsdk.inc
  inc2l cabinet.inc
  inc2l ccfapi32.inc
  inc2l certadm.inc
  inc2l certidl.inc
  inc2l cfgmgr.inc
  inc2l cfgmgr32.inc
  inc2l classpnp.inc
  inc2l clusapi.inc
  inc2l comctl32.inc
  inc2l comdlg32.inc
  inc2l compstui.inc
  inc2l comsvcs.inc
  inc2l credui.inc
  inc2l crypt32.inc
  inc2l cryptdll.inc
  inc2l cryptnet.inc
  inc2l cryptui.inc
  inc2l cscdll.inc
  inc2l csq.inc
  inc2l d3d8.inc
  inc2l d3dpmesh.inc
  inc2l d3dx.inc
  inc2l d3dx8.inc
  inc2l d3dx8d.inc
  inc2l d3dxof.inc
  inc2l DateTime.inc
  inc2l ddraw.inc
  inc2l debug.inc
  inc2l decoder.inc
  inc2l delayimp.inc
  inc2l delayload.inc
  inc2l devmgr.inc
  inc2l dflayout.inc
  inc2l dhcpcsvc.inc
  inc2l dinput.inc
  inc2l dinput8.inc
  inc2l dlcapi.inc
  inc2l dnsapi.inc
  inc2l dnscrcli.inc
  inc2l dnslib.inc
  inc2l dnsperf.inc
  inc2l dnsrpc.inc
  inc2l dnsrslvr.inc
  inc2l dplay.inc
  inc2l dplayx.inc
  inc2l dpmodemx.inc
  inc2l dpserial.inc
  inc2l dpwsock.inc
  inc2l dpwsockx.inc
  inc2l drmk.inc
  inc2l dsetup.inc
  inc2l dsound.inc
  inc2l dsprop.inc
  inc2l dssec.inc
  inc2l dststlog.inc
  inc2l dsuiext.inc
  inc2l dtchelp.inc
  inc2l dxapi.inc
  inc2l elfapi.inc
  inc2l esent.inc
  inc2l excppkg.inc
  inc2l exsup.inc
  inc2l fci.inc
  inc2l fdi.inc
  inc2l feclient.inc
  inc2l framedyd.inc
  inc2l framedyn.inc
  inc2l ftsrch.inc
  inc2l gapi32.inc
  inc2l gdi32.inc
  inc2l gdiplus.inc
  inc2l glaux.inc
  inc2l glmf32.inc
  inc2l glu32.inc
  inc2l gpedit.inc
  inc2l hal.inc
  inc2l hcaport.inc
  inc2l hid.inc
  inc2l hidclass.inc
  inc2l hidparse.inc
  inc2l hlink.inc
  inc2l hpmon.inc
  inc2l htmlhelp.inc
  inc2l iashlpr.inc
  inc2l icm32.inc
  inc2l icmui.inc
  inc2l iesetup.inc
  inc2l imagehlp.inc
  inc2l imgutil.inc
  inc2l imm32.inc
  inc2l inseng.inc
  inc2l iphlpapi.inc
  inc2l iprop.inc
  inc2l kerbcli.inc
  inc2l kernel32.inc
  inc2l kernl32p.inc
  inc2l ks.inc
  inc2l ksecdd.inc
  inc2l ksproxy.inc
  inc2l ksuser.inc
  inc2l libc.inc
  inc2l libcpsx.inc
  inc2l llsrpc.inc
  inc2l loadperf.inc
  inc2l logonsrv.inc
  inc2l lsadll.inc
  inc2l lsasrv.inc
  inc2l lsasrvd.inc
  inc2l lvcodek.inc
  inc2l lz32.inc
  inc2l mapi32.inc
  inc2l mcd.inc
  inc2l mcd32.inc
  inc2l mcdsrv32.inc
  inc2l mciole32.inc
  inc2l mgmtapi.inc
  inc2l miglib.inc
  inc2l mmc.inc
  inc2l mobsync.inc
  inc2l mobsyncp.inc
  inc2l mpr.inc
  inc2l mprapi.inc
  inc2l mprsnap.inc
  inc2l mqmail.inc
  inc2l mqrt.inc
  inc2l msacm32.inc
  inc2l msasn1.inc
  inc2l mscms.inc
  inc2l msdmo.inc
  inc2l msi.inc
  inc2l msimg32.inc
  inc2l mspbase.inc
  inc2l msports.inc
  inc2l msrating.inc
  inc2l mssachlp.inc
  inc2l mstask.inc
  inc2l msv1_0.inc
  inc2l mswsock.inc
  inc2l mtx.inc
  inc2l nal.inc
  inc2l nddeapi.inc
  inc2l ndis.inc
  inc2l ndrd.inc
  inc2l netapi32.inc
  inc2l netlib.inc
  inc2l netrap.inc
  inc2l netui2.inc
  inc2l newdev.inc
  inc2l nia35det.inc
  inc2l nibcdet.inc
  inc2l nlmonlib.inc
  inc2l nmapi.inc
  inc2l nmsupp.inc
  inc2l npptools.inc
  inc2l nt.inc
  inc2l ntdll.inc
  inc2l ntdsa.inc
  inc2l ntdsapi.inc
  inc2l ntdsatq.inc
  inc2l ntdsbcli.inc
  inc2l ntdsetup.inc
  inc2l ntfrsapi.inc
  inc2l ntlanman.inc
  inc2l ntlanui.inc
  inc2l ntlsapi.inc
  inc2l ntmarta.inc
  inc2l ntmsapi.inc
  inc2l ntoskrnl.inc exe
  inc2l ntquery.inc
  inc2l ntstrsafe.inc
  inc2l ntvdm.inc
  inc2l nwmon.inc
  inc2l nwprint.inc
  inc2l nwsaplib.inc
  inc2l nwsevent.inc
  inc2l nwslib.inc
  inc2l odbc32.inc
  inc2l odbccp32.inc
  inc2l ole32.inc
  inc2l oleacc.inc
  inc2l oleaut32.inc
  inc2l olecli32.inc
  inc2l oledlg.inc
  inc2l olepro32.inc
  inc2l olesvr32.inc
  inc2l opengl32.inc
  inc2l oprghdlr.inc
  inc2l parser.inc
  inc2l pciidex.inc
  inc2l pdh.inc
  inc2l portcls.inc
  inc2l powrprof.inc
  inc2l psapi.inc
  inc2l psxdll.inc
  inc2l psxrtl.inc
  inc2l ptilink.inc
  inc2l qosname.inc
  inc2l quartz.inc
  inc2l query.inc
  inc2l r81wdet.inc
  inc2l randlib.inc
  inc2l randlibk.inc
  inc2l rasapi32.inc
  inc2l rasdlg.inc
  inc2l rassapi.inc
  inc2l resutils.inc
  inc2l rpcexts.inc
  inc2l rpcndr.inc
  inc2l rpcns4.inc
  inc2l rpcproxy.inc
  inc2l rpcrt4.inc
  inc2l rpcutil.inc
  inc2l rsa32sdk2.inc
  inc2l rtm.inc
  inc2l rtutils.inc
  inc2l rxapi.inc
  inc2l rxcommon.inc
  inc2l samlib.inc
  inc2l samsrv.inc
  inc2l scarddlg.inc
  inc2l scecli.inc
  inc2l scesrv.inc
  inc2l schannel.inc
  inc2l sclogon.inc
  inc2l scrnsave.inc
  inc2l scrnsavw.inc
  inc2l scsiport.inc
  inc2l scsiwmi.inc
  inc2l sdbus.inc
  inc2l secur32.inc
  inc2l security.inc
  inc2l sens.inc
  inc2l sensapi.inc
  inc2l setupapi.inc
  inc2l setupexts.inc
  inc2l sfc.inc
  inc2l sfcfiles.inc
  inc2l shell32.inc
  inc2l shfolder.inc
  inc2l shlwapi.inc
  inc2l sisbkup.inc
  inc2l smbtrsup.inc
  inc2l smclib.inc
  inc2l snmpapi.inc
  inc2l spoolss.inc
  inc2l sporder.inc
  inc2l srclient.inc
  inc2l ssdpapi.inc
  inc2l stdunk.inc
  inc2l sti.inc
  inc2l storport.inc
  inc2l stream.inc
  inc2l streams.inc
  inc2l strmbasd.inc
  inc2l strmbase.inc
  inc2l syssetup.inc
  inc2l tape.inc
  inc2l tapi32.inc
  inc2l tapi32l.inc
  inc2l tcpip.inc
  inc2l tcpip6.inc
  inc2l tdi.inc
  inc2l thunk32.inc
  inc2l traffic.inc
  inc2l tsec.inc
  inc2l twain_32.inc
  inc2l umpdddi.inc
  inc2l umpnplib.inc
  inc2l uniime.inc
  inc2l urlmon.inc
  inc2l usbcamd.inc
  inc2l usbcamd2.inc
  inc2l usbd.inc
  inc2l user32.inc
  inc2l userenv.inc
  inc2l usp10.inc
  inc2l uxtheme.inc
  inc2l vccomsup.inc
  inc2l vdmdbg.inc
  inc2l version.inc
  inc2l vfw32.inc
  inc2l videoprt.inc
  inc2l wdm.inc
  inc2l wdmsec.inc
  inc2l wiaservc.inc
  inc2l wiautil.inc
  inc2l win32k.inc
  inc2l winfax.inc
  inc2l wininet.inc
  inc2l winmm.inc
  inc2l winppi.inc
  inc2l winscard.inc
  inc2l winspool.inc drv
  inc2l winsta.inc
  inc2l winstrm.inc
  inc2l wintrust.inc
  inc2l wldap32.inc
  inc2l wmilib.inc
  inc2l wmip.inc
  inc2l wmvcore.inc
  inc2l wow32.inc
  inc2l ws2_32.inc
  inc2l wshisotp.inc
  inc2l wsnmp32.inc
  inc2l wsock32.inc
  inc2l wtsapi32.inc
  inc2l xactsrv.inc
  inc2l xaswitch.inc
  inc2l xolehlp.inc

    del ntoskrnl.exe
    del winspool.drv

move *.lib \masm32\lib