; --------------------------------------------------------------------------------------------------
;                          dpmodemx.inc Copyright The MASM32 SDK 1998-2010
; --------------------------------------------------------------------------------------------------

IFNDEF DPMODEMX_INC
DPMODEMX_INC equ <1>

SPInit PROTO STDCALL :DWORD

ELSE
  echo -------------------------------------------
  echo WARNING duplicate include file dpmodemx.inc
  echo -------------------------------------------
ENDIF
