; --------------------------------------------------------------------------------------------------
;                          dpserial.inc Copyright The MASM32 SDK 1998-2010
; --------------------------------------------------------------------------------------------------

IFNDEF DPSERIAL_INC
DPSERIAL_INC equ <1>

  ; CreateNewDirectPlay arg type unknown

ELSE
  echo -------------------------------------------
  echo WARNING duplicate include file dpserial.inc
  echo -------------------------------------------
ENDIF
