; --------------------------------------------------------------------------------------------------
;                           dpwsock.inc Copyright The MASM32 SDK 1998-2010
; --------------------------------------------------------------------------------------------------

IFNDEF DPWSOCK_INC
DPWSOCK_INC equ <1>

  ; CreateNewDirectPlay arg type unknown

ELSE
  echo ------------------------------------------
  echo WARNING duplicate include file dpwsock.inc
  echo ------------------------------------------
ENDIF
