; --------------------------------------------------------------------------------------------------
;                          dststlog.inc Copyright The MASM32 SDK 1998-2010
; --------------------------------------------------------------------------------------------------

IFNDEF DSTSTLOG_INC
DSTSTLOG_INC equ <1>

  ; PrintLog arg type unknown

ELSE
  echo -------------------------------------------
  echo WARNING duplicate include file dststlog.inc
  echo -------------------------------------------
ENDIF
