; --------------------------------------------------------------------------------------------------
;                          nwsevent.inc Copyright The MASM32 SDK 1998-2010
; --------------------------------------------------------------------------------------------------

IFNDEF NWSEVENT_INC
NWSEVENT_INC equ <1>

DummyEntryPoint PROTO STDCALL

ELSE
  echo -------------------------------------------
  echo WARNING duplicate include file nwsevent.inc
  echo -------------------------------------------
ENDIF
