EnumerateLoadedModules proto :dword, :dword, :dword
EnumerateLoadedModules64 proto :dword, :dword, :dword
ExtensionApiVersion proto
FindDebugInfoFile proto :dword, :dword, :dword
FindDebugInfoFileEx proto :dword, :dword, :dword, :dword, :dword
FindExecutableImage proto :dword, :dword, :dword
FindExecutableImageEx proto :dword, :dword, :dword, :dword, :dword
FindFileInSearchPath proto :dword, :dword, :dword, :dword, :dword, :dword, :dword
GetTimestampForLoadedLibrary proto :dword
ImageDirectoryEntryToData proto :dword, :dword, :dword, :dword
ImageDirectoryEntryToDataEx proto :dword, :dword, :dword, :dword, :dword
ImageNtHeader proto :dword
ImageRvaToSection proto :dword, :dword, :dword
ImageRvaToVa proto :dword, :dword, :dword, :dword
ImagehlpApiVersion proto
ImagehlpApiVersionEx proto :dword
MakeSureDirectoryPathExists proto :dword
MapDebugInformation proto :dword, :dword, :dword
SearchTreeForFile proto :dword, :dword, :dword
StackWalk proto :dword, :dword, :dword, :dword, :dword, :dword, :dword, :dword, :dword
StackWalk64 proto :dword, :dword, :dword, :dword, :dword, :dword, :dword, :dword, :dword
SymCleanup proto :dword
SymEnumerateModules proto :dword, :dword, :dword
SymEnumerateModules64 proto :dword, :dword, :dword
SymEnumerateSymbols proto :dword, :dword, :dword, :dword
SymEnumerateSymbols64 proto :dword, :dword, :dword, :dword
SymEnumerateSymbolsW proto :dword, :dword, :dword, :dword
SymEnumerateSymbolsW64 proto :dword, :dword, :dword, :dword
SymFunctionTableAccess proto :dword, :dword
SymFunctionTableAccess64 proto :dword, :dword
SymGetLineFromAddr proto :dword, :dword, :dword, :dword
SymGetLineFromAddr64 proto :dword, :dword, :dword, :dword
SymGetLineFromName proto :dword, :dword, :dword, :dword, :dword, :dword
SymGetLineFromName64 proto :dword, :dword, :dword, :dword, :dword, :dword
SymGetLineNext proto :dword, :dword
SymGetLineNext64 proto :dword, :dword
SymGetLinePrev proto :dword, :dword
SymGetLinePrev64 proto :dword, :dword
SymGetModuleBase proto :dword, :dword
SymGetModuleBase64 proto :dword, :dword
SymGetModuleInfo proto :dword, :dword, :dword
SymGetModuleInfo64 proto :dword, :dword, :dword
SymGetModuleInfoEx proto :dword, :dword, :dword, :dword, :dword, :dword, :dword
SymGetModuleInfoEx64 proto :dword, :dword, :dword, :dword, :dword, :dword, :dword
SymGetModuleInfoW proto :dword, :dword, :dword
SymGetModuleInfoW64 proto :dword, :dword, :dword
SymGetOptions proto
SymGetSearchPath proto :dword, :dword, :dword
SymGetSymFromAddr proto :dword, :dword, :dword, :dword
SymGetSymFromAddr64 proto :dword, :dword, :dword, :dword
SymGetSymFromName proto :dword, :dword, :dword
SymGetSymFromName64 proto :dword, :dword, :dword
SymGetSymNext proto :dword, :dword
SymGetSymNext64 proto :dword, :dword
SymGetSymPrev proto :dword, :dword
SymGetSymPrev64 proto :dword, :dword
SymGetSymbolInfo proto :dword, :dword, :dword, :dword, :dword, :dword, :dword
SymGetSymbolInfo64 proto :dword, :dword, :dword, :dword, :dword, :dword, :dword
SymInitialize proto :dword, :dword, :dword
SymLoadModule proto :dword, :dword, :dword, :dword, :dword, :dword
SymLoadModule64 proto :dword, :dword, :dword, :dword, :dword, :dword
SymMatchFileName proto :dword, :dword, :dword, :dword
SymRegisterCallback proto :dword, :dword, :dword
SymRegisterCallback64 proto :dword, :dword, :dword
SymRegisterFunctionEntryCallback proto :dword, :dword, :dword
SymRegisterFunctionEntryCallback64 proto :dword, :dword, :dword
SymSetOptions proto :dword
SymSetSearchPath proto :dword, :dword
SymUnDName proto :dword, :dword, :dword
SymUnDName64 proto :dword, :dword, :dword
SymUnloadModule proto :dword, :dword
SymUnloadModule64 proto :dword, :dword
UnDecorateSymbolName proto :dword, :dword, :dword, :dword
UnmapDebugInformation proto :dword
WinDbgExtensionDllInit proto
sym proto